apiVersion: securitytower.io/v1alpha1
kind: Cluster
metadata:
  name: pintc01003h040401050l001
spec:
  tenant: SSP
  contact:
    email: josh.vermast@finastra.com
  configuration:
    description: SSP Internal/Dev Cluster
    geographicLocation: Azure - EastUS
    production: false
    securityLevel: internal
  policies:
    path: cluster/policies
  namespaces:
    - path: cluster/namespaces
